Allow to pass in custom environment variables.
jgraham/rust_mozrunner pull request #11
Opened 2017-08-18 05:50 UTC by whimboo

@andreastt and @jgraham maybe you can give feedback? It all works fine, but I'm not sure if we should use `String` or `str` here for the `HashMap` entries. Using `String` feels awkward when it comes to the addition. Here an example for [bug 1388249](https://bugzilla.mozilla.org/show_bug.cgi?id=1388249):

```
runner.envs().insert("MOZ_CRASHREPORTER".to_string(), "1".to_string());
runner.envs().insert("MOZ_CRASHREPORTER_NO_REPORT".to_string(), "1".to_string());
runner.envs().insert("MOZ_CRASHREPORTER_SHUTDOWN".to_string(), "1".to_string());
```

2017-08-18 12:52 UTC, jgraham requested changes

2017-08-18 12:52 UTC, jgraham commented on src/runner.rs
> +use mozprofile::prefreader::PrefReaderError;
Rust conventions are not Python conventions here. Please just leave this as a sorted list.

2017-08-18 13:05 UTC, whimboo commented on src/runner.rs
> +use mozprofile::prefreader::PrefReaderError;
Done.

2017-08-18 13:22 UTC, jgraham approved these changes

2017-08-18 13:22 UTC, merged

2017-08-21 06:59 UTC, whimboo commented
@jgraham would you mind releasing a new version to crates.io? Thanks.