Only add a -profile argument if one is not already present.
jgraham/rust_mozrunner pull request #9
Opened 2017-06-12 16:19 UTC by jgraham

Previously we unconditionally added a -profile argument. Instead we
should do this only if there is not a user-supplied profile.

2017-06-12 16:19 UTC, jgraham commented
r? @andreastt

2017-06-12 16:25 UTC, andreastt approved these changes
This is great, and simpler than I thought it would be. Not sure why I thought it would be hard though…

2017-06-12 16:25 UTC, andreastt commented on src/runner.rs
> +            arg.starts_with("/profile")
Do we really pick up `/profile` on Windows?

2017-06-12 16:30 UTC, jgraham commented on src/runner.rs
> +            arg.starts_with("/profile")
Yes.

I guess this doesn't handle `-P` and I don't know if the handling of `-ProfileManager` is right (I guess it is?).

2017-06-12 22:17 UTC, jgraham commented
This is less simple but more correct.

2017-06-13 17:40 UTC, andreastt requested changes

2017-06-13 17:40 UTC, andreastt commented on src/runner.rs
> +        if !self.args.iter().any(|x| is_profile_arg(x)) {
```rust
if !self.args.iter().any(is_profile_arg) {
```

2017-06-13 17:40 UTC, andreastt commented on src/runner.rs
> +pub fn is_profile_arg(arg: &str) -> bool {
Documentation, please.

2017-06-13 17:40 UTC, andreastt commented on src/runner.rs
> +            }
This brace is placed in the wrong block.

2017-06-13 17:40 UTC, andreastt commented on src/runner.rs
> +        c == '/' || c == '-'
I don’t think we support `/` as a flag prefix on macOS.

2017-06-14 15:37 UTC, jgraham commented on src/runner.rs
> +        if !self.args.iter().any(|x| is_profile_arg(x)) {
Surprisingly, no. That seems to pass an `&String` rather than an `&str` so it doesn't type check.

2017-06-14 15:39 UTC, andreastt commented on src/runner.rs
> +        if !self.args.iter().any(|x| is_profile_arg(x)) {
Aha, perhaps there is some type coercion going on here that it isn’t able to figure out if you pass a function by reference.

2017-06-14 15:40 UTC, andreastt approved these changes

2017-06-14 15:41 UTC, merged